import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { atomicWriteTextFile } from '../core/fs';
import { parseMarkdownRows } from './markdown-table';
import { findVocabularyDomain } from './controlled-vocabulary';

/**
 * FD-012: first bounded state-first experiment (0.5 RFC section 9 gate).
 *
 * `.hadara/state/slices.json` is the canonical slice store (Domain A of the
 * state-first RFC: a per-file `rev` guards concurrent CLI writes) and
 * `docs/DEVELOPMENT_SLICES.md` becomes a fully generated Tier 1 projection.
 * Ownership contract: the rendered file is never hand-edited; drift is
 * detected (never silently overwritten) and resolved explicitly through
 * `hadara slice render` or `hadara slice migrate`.
 */

export const SLICES_STATE_PATH = '.hadara/state/slices.json';
export const SLICES_PROJECTION_PATH = 'docs/DEVELOPMENT_SLICES.md';
export const SLICES_GENERATED_MARKER = '<!-- generated by hadara slice render; edit via hadara slice commands, not by hand -->';

export interface SliceEntry {
  id: string;
  title: string;
  order: number;
  capsule: string | null;
  status: string;
  purpose: string;
  doneEvidence: string;
  depends: string[];
}

export interface SlicesStateFile {
  schemaVersion: 'hadara.slicesState.v1';
  rev: number;
  slices: SliceEntry[];
}

export interface SliceIssue {
  severity: 'error' | 'warning';
  code: string;
  message: string;
  path?: string;
  field?: string;
  received?: string;
  allowedValues?: string[];
}

export interface SliceReport {
  schemaVersion: 'hadara.slice.report.v1';
  command: 'slice.add' | 'slice.set' | 'slice.list' | 'slice.migrate' | 'slice.render';
  mode: 'dry-run' | 'execute' | 'read-only';
  ok: boolean;
  statePath: typeof SLICES_STATE_PATH;
  projectionPath: typeof SLICES_PROJECTION_PATH;
  statePresent: boolean;
  rev: number | null;
  slices: SliceEntry[];
  writes: string[];
  projection: {
    written: boolean;
    driftDetected: boolean;
    renderedHash: string | null;
    fileHash: string | null;
  };
  issues: SliceIssue[];
}

export interface SliceAddOptions {
  id: string;
  title: string;
  order?: number;
  capsule?: string;
  status?: string;
  purpose?: string;
  doneEvidence?: string;
  depends?: string[];
}

export interface SliceSetOptions {
  id: string;
  title?: string;
  order?: number;
  capsule?: string;
  status?: string;
  purpose?: string;
  doneEvidence?: string;
  depends?: string[];
}

export function readSlicesState(projectRoot: string): { present: boolean; state: SlicesStateFile | null; issues: SliceIssue[] } {
  const filePath = path.join(projectRoot, SLICES_STATE_PATH);
  if (!fs.existsSync(filePath)) return { present: false, state: null, issues: [] };
  try {
    const parsed = JSON.parse(fs.readFileSync(filePath, 'utf8')) as SlicesStateFile;
    if (parsed.schemaVersion !== 'hadara.slicesState.v1' || !Array.isArray(parsed.slices)) {
      return {
        present: true,
        state: null,
        issues: [{ severity: 'error', code: 'SLICES_STATE_INVALID', path: SLICES_STATE_PATH, message: 'Slices state file has an unsupported shape.' }]
      };
    }
    return { present: true, state: parsed, issues: [] };
  } catch (error) {
    return {
      present: true,
      state: null,
      issues: [{ severity: 'error', code: 'SLICES_STATE_INVALID_JSON', path: SLICES_STATE_PATH, message: `Slices state JSON could not be parsed: ${error instanceof Error ? error.message : String(error)}` }]
    };
  }
}

function writeSlicesState(projectRoot: string, slices: SliceEntry[], previousRev: number | null): SlicesStateFile {
  const next: SlicesStateFile = {
    schemaVersion: 'hadara.slicesState.v1',
    rev: (previousRev ?? 0) + 1,
    slices: [...slices].sort((a, b) => a.order - b.order || a.id.localeCompare(b.id))
  };
  atomicWriteTextFile(projectRoot, SLICES_STATE_PATH, `${JSON.stringify(next, null, 2)}\n`);
  return next;
}

export function renderDevelopmentSlices(state: SlicesStateFile): string {
  const lines = [
    '# DEVELOPMENT_SLICES',
    '',
    SLICES_GENERATED_MARKER,
    '',
    `Canonical slice state lives in \`${SLICES_STATE_PATH}\` (rev ${state.rev}). Use \`hadara slice add|set|list\` to change it and \`hadara slice render\` to regenerate this file.`,
    '',
    '| Order | Slice | Capsule | Purpose | Done Evidence | Status |',
    '|---|---|---|---|---|---|'
  ];
  const sorted = [...state.slices].sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
  for (const slice of sorted) {
    const sliceLabel = slice.title ? `${slice.id}: ${slice.title}` : slice.id;
    const depends = slice.depends.length > 0 ? ` (depends: ${slice.depends.join(', ')})` : '';
    lines.push(
      `| ${slice.order} | ${sliceLabel}${depends} | ${slice.capsule ?? 'TBD'} | ${slice.purpose || 'TBD'} | ${slice.doneEvidence || 'TBD'} | ${slice.status} |`
    );
  }
  lines.push('');
  return lines.join('\n');
}

function hashText(value: string): string {
  return `sha256:${crypto.createHash('sha256').update(value, 'utf8').digest('hex')}`;
}

export function slicesProjectionDrift(projectRoot: string, state: SlicesStateFile): { driftDetected: boolean; renderedHash: string; fileHash: string | null } {
  const rendered = renderDevelopmentSlices(state);
  const filePath = path.join(projectRoot, SLICES_PROJECTION_PATH);
  if (!fs.existsSync(filePath)) return { driftDetected: false, renderedHash: hashText(rendered), fileHash: null };
  const fileContent = fs.readFileSync(filePath, 'utf8');
  return {
    driftDetected: fileContent !== rendered,
    renderedHash: hashText(rendered),
    fileHash: hashText(fileContent)
  };
}

function validateStatus(status: string, issues: SliceIssue[]): boolean {
  const domain = findVocabularyDomain('slices.status');
  const allowed = domain?.allowed ?? [];
  if (allowed.includes(status)) return true;
  issues.push({
    severity: 'error',
    code: 'SLICE_STATUS_INVALID_TOKEN',
    field: 'status',
    received: status,
    allowedValues: [...allowed],
    message: `Slice status has invalid value: ${status}. Allowed values: ${allowed.join(', ')}.`
  });
  return false;
}

/**
 * Ownership-contract guard shared by mutations: after a state write we only
 * auto-regenerate the projection when the current file still matches the
 * previous render (or is absent). A hand-edited projection is reported as
 * drift and left untouched — resolving it requires an explicit
 * `hadara slice render` (discard) or `hadara slice migrate` (import).
 */
function projectAfterMutation(projectRoot: string, previous: SlicesStateFile | null, next: SlicesStateFile, issues: SliceIssue[]): SliceReport['projection'] {
  const filePath = path.join(projectRoot, SLICES_PROJECTION_PATH);
  const rendered = renderDevelopmentSlices(next);
  const fileExists = fs.existsSync(filePath);
  if (fileExists) {
    const currentContent = fs.readFileSync(filePath, 'utf8');
    // With no previous state (bootstrap add), any existing projection file is
    // hand-authored legacy content — same drift treatment, never overwrite.
    if (!previous || currentContent !== renderDevelopmentSlices(previous)) {
      issues.push({
        severity: 'warning',
        code: 'SLICES_RENDER_DRIFT_DETECTED',
        path: SLICES_PROJECTION_PATH,
        message: `${SLICES_PROJECTION_PATH} was edited outside the render pipeline; the state change was saved but the projection was NOT overwritten. Run \`hadara slice render\` to discard the manual edit or \`hadara slice migrate --execute\` to import it into state first.`
      });
      return { written: false, driftDetected: true, renderedHash: hashText(rendered), fileHash: hashText(currentContent) };
    }
  }
  atomicWriteTextFile(projectRoot, SLICES_PROJECTION_PATH, rendered);
  return { written: true, driftDetected: false, renderedHash: hashText(rendered), fileHash: hashText(rendered) };
}

function baseReport(command: SliceReport['command'], mode: SliceReport['mode']): SliceReport {
  return {
    schemaVersion: 'hadara.slice.report.v1',
    command,
    mode,
    ok: false,
    statePath: SLICES_STATE_PATH,
    projectionPath: SLICES_PROJECTION_PATH,
    statePresent: false,
    rev: null,
    slices: [],
    writes: [],
    projection: { written: false, driftDetected: false, renderedHash: null, fileHash: null },
    issues: []
  };
}

export function createSliceListReport(projectRoot: string): SliceReport {
  const report = baseReport('slice.list', 'read-only');
  const { present, state, issues } = readSlicesState(projectRoot);
  report.statePresent = present;
  report.issues.push(...issues);
  if (state) {
    report.rev = state.rev;
    report.slices = state.slices;
    const drift = slicesProjectionDrift(projectRoot, state);
    report.projection = { written: false, ...drift };
    if (drift.driftDetected) {
      report.issues.push({
        severity: 'warning',
        code: 'SLICES_RENDER_DRIFT_DETECTED',
        path: SLICES_PROJECTION_PATH,
        message: `${SLICES_PROJECTION_PATH} does not match the rendered slice state. Run \`hadara slice render\` to regenerate it or \`hadara slice migrate --execute\` to import the file into state.`
      });
    }
  } else if (!present) {
    report.issues.push({
      severity: 'warning',
      code: 'SLICES_STATE_MISSING',
      path: SLICES_STATE_PATH,
      message: `No slices state file. Bootstrap one with \`hadara slice migrate --execute\` (from an existing ${SLICES_PROJECTION_PATH}) or \`hadara slice add\`.`
    });
  }
  report.ok = report.issues.every((issue) => issue.severity !== 'error');
  return report;
}

export function createSliceAddReport(projectRoot: string, options: SliceAddOptions): SliceReport {
  const report = baseReport('slice.add', 'execute');
  const { present, state, issues } = readSlicesState(projectRoot);
  report.statePresent = present;
  report.issues.push(...issues);
  if (present && !state) {
    report.ok = false;
    return report;
  }
  const id = options.id.trim();
  if (!id) report.issues.push({ severity: 'error', code: 'SLICE_ID_REQUIRED', message: 'slice add requires --id.' });
  if (state?.slices.some((slice) => slice.id === id)) {
    report.issues.push({ severity: 'error', code: 'SLICE_ID_EXISTS', message: `Slice ${id} already exists. Use \`hadara slice set --id ${id}\` to change it.` });
  }
  const status = options.status ?? 'not-started';
  validateStatus(status, report.issues);
  if (report.issues.some((issue) => issue.severity === 'error')) return report;

  const maxOrder = state ? Math.max(0, ...state.slices.map((slice) => slice.order)) : 0;
  const entry: SliceEntry = {
    id,
    title: options.title.trim(),
    order: options.order ?? maxOrder + 1,
    capsule: options.capsule?.trim() || null,
    status,
    purpose: options.purpose?.trim() ?? '',
    doneEvidence: options.doneEvidence?.trim() ?? '',
    depends: options.depends ?? []
  };
  const next = writeSlicesState(projectRoot, [...(state?.slices ?? []), entry], state?.rev ?? null);
  report.statePresent = true;
  report.rev = next.rev;
  report.slices = next.slices;
  report.writes.push(SLICES_STATE_PATH);
  report.projection = projectAfterMutation(projectRoot, state, next, report.issues);
  if (report.projection.written) report.writes.push(SLICES_PROJECTION_PATH);
  report.ok = report.issues.every((issue) => issue.severity !== 'error');
  return report;
}

export function createSliceSetReport(projectRoot: string, options: SliceSetOptions): SliceReport {
  const report = baseReport('slice.set', 'execute');
  const { present, state, issues } = readSlicesState(projectRoot);
  report.statePresent = present;
  report.issues.push(...issues);
  if (!state) {
    report.issues.push({ severity: 'error', code: 'SLICES_STATE_MISSING', path: SLICES_STATE_PATH, message: 'No slices state file; run `hadara slice migrate --execute` or `hadara slice add` first.' });
    return report;
  }
  const entry = state.slices.find((slice) => slice.id === options.id.trim());
  if (!entry) {
    report.issues.push({
      severity: 'error',
      code: 'SLICE_NOT_FOUND',
      field: 'id',
      received: options.id,
      allowedValues: state.slices.map((slice) => slice.id),
      message: `Slice ${options.id} was not found. Known slices: ${state.slices.map((slice) => slice.id).join(', ')}.`
    });
    return report;
  }
  if (options.status !== undefined && !validateStatus(options.status, report.issues)) return report;

  const updated: SliceEntry = {
    ...entry,
    title: options.title?.trim() ?? entry.title,
    order: options.order ?? entry.order,
    capsule: options.capsule !== undefined ? options.capsule.trim() || null : entry.capsule,
    status: options.status ?? entry.status,
    purpose: options.purpose?.trim() ?? entry.purpose,
    doneEvidence: options.doneEvidence?.trim() ?? entry.doneEvidence,
    depends: options.depends ?? entry.depends
  };
  const next = writeSlicesState(projectRoot, state.slices.map((slice) => (slice.id === entry.id ? updated : slice)), state.rev);
  report.rev = next.rev;
  report.slices = next.slices;
  report.writes.push(SLICES_STATE_PATH);
  report.projection = projectAfterMutation(projectRoot, state, next, report.issues);
  if (report.projection.written) report.writes.push(SLICES_PROJECTION_PATH);
  report.ok = report.issues.every((issue) => issue.severity !== 'error');
  return report;
}

export function createSliceRenderReport(projectRoot: string): SliceReport {
  const report = baseReport('slice.render', 'execute');
  const { present, state, issues } = readSlicesState(projectRoot);
  report.statePresent = present;
  report.issues.push(...issues);
  if (!state) {
    report.issues.push({ severity: 'error', code: 'SLICES_STATE_MISSING', path: SLICES_STATE_PATH, message: 'No slices state file to render from; run `hadara slice migrate --execute` or `hadara slice add` first.' });
    return report;
  }
  report.rev = state.rev;
  report.slices = state.slices;
  const rendered = renderDevelopmentSlices(state);
  atomicWriteTextFile(projectRoot, SLICES_PROJECTION_PATH, rendered);
  report.writes.push(SLICES_PROJECTION_PATH);
  report.projection = { written: true, driftDetected: false, renderedHash: hashText(rendered), fileHash: hashText(rendered) };
  report.ok = true;
  return report;
}

export interface SliceMigrateOptions {
  mode: 'dry-run' | 'execute';
}

export function createSliceMigrateReport(projectRoot: string, options: SliceMigrateOptions): SliceReport {
  const report = baseReport('slice.migrate', options.mode);
  const filePath = path.join(projectRoot, SLICES_PROJECTION_PATH);
  const existing = readSlicesState(projectRoot);
  report.statePresent = existing.present;
  if (!fs.existsSync(filePath)) {
    report.issues.push({ severity: 'error', code: 'SLICES_PROJECTION_MISSING', path: SLICES_PROJECTION_PATH, message: `${SLICES_PROJECTION_PATH} does not exist; nothing to migrate.` });
    return report;
  }

  const rows = parseMarkdownRows(fs.readFileSync(filePath, 'utf8'));
  const entries: SliceEntry[] = [];
  let fallbackOrder = 0;
  for (const cells of rows) {
    const orderCell = (cells[0] ?? '').trim();
    if (!/^\d+$/.test(orderCell)) {
      if (orderCell && orderCell !== 'Order' && orderCell !== '---') {
        report.issues.push({ severity: 'warning', code: 'SLICE_MIGRATE_ROW_SKIPPED', path: SLICES_PROJECTION_PATH, message: `Skipped non-slice row starting with "${orderCell.slice(0, 40)}".` });
      }
      continue;
    }
    fallbackOrder += 1;
    const sliceCell = (cells[1] ?? '').trim();
    const idMatch = /^([A-Za-z0-9._-]+)\s*[:|]?/.exec(sliceCell);
    const dependsMatch = /\(depends:\s*([^)]+)\)/.exec(sliceCell);
    const capsuleCell = (cells[2] ?? '').trim();
    const capsuleMatch = /(T-\d{4})/.exec(capsuleCell);
    const statusCell = (cells[5] ?? '').trim();
    const doneMarker = /\(done\)/i.test(capsuleCell) || /^done\b/i.test(statusCell);
    const status = statusCell && findVocabularyDomain('slices.status')?.allowed.includes(statusCell)
      ? statusCell
      : doneMarker
        ? 'done'
        : capsuleMatch
          ? 'in-progress'
          : 'not-started';
    entries.push({
      id: idMatch?.[1] ?? `slice-${fallbackOrder}`,
      title: sliceCell.replace(/\(depends:[^)]+\)/, '').replace(/^([A-Za-z0-9._-]+)\s*:\s*/, '').trim(),
      order: Number.parseInt(orderCell, 10),
      capsule: capsuleMatch?.[1] ?? null,
      status,
      purpose: (cells[3] ?? '').trim().replace(/^TBD$/i, ''),
      doneEvidence: (cells[4] ?? '').trim().replace(/^TBD$/i, ''),
      depends: dependsMatch ? dependsMatch[1].split(',').map((token) => token.trim()).filter(Boolean) : []
    });
  }
  if (entries.length === 0) {
    report.issues.push({ severity: 'error', code: 'SLICE_MIGRATE_NO_ROWS', path: SLICES_PROJECTION_PATH, message: 'No slice rows could be parsed from the projection file.' });
    return report;
  }

  report.slices = [...entries].sort((a, b) => a.order - b.order || a.id.localeCompare(b.id));
  if (options.mode === 'execute') {
    const next = writeSlicesState(projectRoot, entries, existing.state?.rev ?? null);
    report.statePresent = true;
    report.rev = next.rev;
    report.slices = next.slices;
    const rendered = renderDevelopmentSlices(next);
    atomicWriteTextFile(projectRoot, SLICES_PROJECTION_PATH, rendered);
    report.writes.push(SLICES_STATE_PATH, SLICES_PROJECTION_PATH);
    report.projection = { written: true, driftDetected: false, renderedHash: hashText(rendered), fileHash: hashText(rendered) };
  }
  report.ok = report.issues.every((issue) => issue.severity !== 'error');
  return report;
}
