import fs from 'node:fs';
import path from 'node:path';
import { ensureDir, readTextIfExists } from '../core/fs';
import { listTaskCapsules } from '../task/task-capsule';

export interface HermesDetection {
  found: string[];
  missing: string[];
}

export interface ContextExportReport {
  schemaVersion: 'hadara.context.export.v1';
  command: 'context.export';
  ok: true;
  format: 'markdown' | 'json';
  mode: 'memory';
  content: string;
  contextPath: null;
  wouldWritePath: '.hadara/context/HADARA_CONTEXT.md';
  issues: ContextExportIssue[];
}

export interface ContextExportIssue {
  severity: 'warning';
  code: 'SUMMARY_ONLY_NOT_IMPLEMENTED';
  message: string;
}

const HERMES_CONTEXT_FILES = ['AGENTS.md', '.hermes.md', 'HERMES.md', 'CLAUDE.md', '.cursorrules'];
const CONTEXT_OUTPUT_PATH = '.hadara/context/HADARA_CONTEXT.md';

export function detectHermesContext(projectRoot: string): HermesDetection {
  const found: string[] = [];
  const missing: string[] = [];

  for (const file of HERMES_CONTEXT_FILES) {
    const filePath = path.join(projectRoot, file);
    if (fs.existsSync(filePath)) found.push(file);
    else missing.push(file);
  }

  return { found, missing };
}

export function buildHadaraContextContent(projectRoot: string): string {
  const sourceFiles = [
    'docs/TASK_BOARD.md',
    'docs/HADARA_WORKFLOW.md',
    'docs/ROADMAP.md',
    'docs/DEVELOPMENT_SLICES.md',
    'docs/CLI_JSON_CONTRACT.md',
    'docs/MCP_BRIDGE_CONTRACT.md',
    'docs/MCP_EVIDENCE_ATTACH_CONTRACT.md',
    'docs/ARCHITECTURE.md',
    'docs/SECURITY_MODEL.md'
  ];

  const taskHandoffFiles = listTaskCapsules(projectRoot)
    .map((task) => path.relative(projectRoot, path.join(task.dir, 'HANDOFF.md')).replace(/\\/g, '/'))
    .filter((relativePath) => fs.existsSync(path.join(projectRoot, relativePath)))
    .sort();
  const sections = [...sourceFiles, ...taskHandoffFiles].map((relativePath) => {
    const content = readTextIfExists(path.join(projectRoot, relativePath)) ?? '_Missing._';
    return `## ${relativePath}\n\n${content}`;
  });

  const output = `# HADARA_CONTEXT

This file is generated by HADARA for Hermes Agent and external agent-harness compatibility.
Do not treat this file as the source of truth; prefer HADARA CLI JSON, MCP read tools, and the referenced docs.
Follow docs/HADARA_WORKFLOW.md for implementation, validation, and session-end procedure.

Agents must:
1. Preserve the portable/project store boundary.
2. Work inside the active Task Capsule.
3. Attach evidence before marking work complete.
4. Keep task-local TASK.md and HANDOFF.md current before stopping.
5. Respect policy decisions for shell/file/git operations.
6. Treat docs/TASK_BOARD.md and task-local HANDOFF.md as the compact continuation state.
7. Prefer stable HADARA read surfaces before scraping raw files: use hadara task status --json for next-work selection and hadara status --json for diagnostics.
8. Use hadara.task.list and hadara.task.read, or hadara task list --json and hadara task status --task <task-id> --json, for task state.
9. Use hadara.policy.evaluate and hadara.harness.validate, or their CLI JSON equivalents, for policy and validation state.
10. Use hadara.context.export for in-memory MCP context export; only hadara hermes export-context writes .hadara/context/HADARA_CONTEXT.md.
11. Treat MCP default mode as read-only; do not assume MCP task mutation, file writes, shell execution, or release/package execution exists.
12. If MCP is unavailable, fall back to CLI JSON commands and then to repository documents.
13. Respect the single active agent/session model; do not assume queues, worker lanes, or multi-agent concurrent execution.
14. Treat policy.evaluate as policy evaluation only, not MCP execution authorization.
15. Treat MCP evidence attachment as disabled by default; it requires explicit server opt-in, per-call approval metadata, and private audit logging.

${sections.join('\n\n---\n\n')}
`;
  return output;
}

export function createContextExportReport(
  projectRoot: string,
  options: { format?: 'markdown' | 'json'; summaryOnly?: boolean } = {}
): ContextExportReport {
  const format = options.format ?? 'markdown';
  const markdown = buildHadaraContextContent(projectRoot);
  const content = format === 'json' ? JSON.stringify({ schemaVersion: 'hadara.context.content.v1', summaryOnly: options.summaryOnly === true, markdown }) : markdown;
  const issues: ContextExportIssue[] =
    options.summaryOnly === true
      ? [
          {
            severity: 'warning',
            code: 'SUMMARY_ONLY_NOT_IMPLEMENTED',
            message: 'summaryOnly is accepted for forward compatibility but currently returns the full context.'
          }
        ]
      : [];
  return {
    schemaVersion: 'hadara.context.export.v1',
    command: 'context.export',
    ok: true,
    format,
    mode: 'memory',
    content,
    contextPath: null,
    wouldWritePath: CONTEXT_OUTPUT_PATH,
    issues
  };
}

export function exportHadaraContext(projectRoot: string): string {
  const contextDir = path.join(projectRoot, '.hadara', 'context');
  ensureDir(contextDir);

  const outputPath = path.join(projectRoot, CONTEXT_OUTPUT_PATH);
  fs.writeFileSync(outputPath, buildHadaraContextContent(projectRoot), 'utf8');
  return outputPath;
}
